-- Additive research and paper release ledger. All writes use the server role.
CREATE TABLE IF NOT EXISTS public.recovery_runs (
  id text PRIMARY KEY, started_at timestamptz NOT NULL DEFAULT now(), finished_at timestamptz,
  from_ts timestamptz NOT NULL, as_of timestamptz NOT NULL, source text NOT NULL,
  status text NOT NULL CHECK(status IN ('running','ok','error')), report jsonb NOT NULL DEFAULT '{}'
);
CREATE TABLE IF NOT EXISTS public.research_observations (
  observation_key text PRIMARY KEY, candidate_key text NOT NULL, strategy_version text NOT NULL,
  source text NOT NULL CHECK(source IN ('yahoo','databento')), provenance text NOT NULL CHECK(provenance IN ('historical-replay','forward')),
  first_seen_at timestamptz NOT NULL DEFAULT now(), signal_ts timestamptz NOT NULL, exit_ts timestamptz,
  payload jsonb NOT NULL, recovery_id text REFERENCES public.recovery_runs(id)
);
CREATE INDEX IF NOT EXISTS research_observations_candidate ON public.research_observations(candidate_key, signal_ts);
ALTER TABLE public.research_observations ADD COLUMN IF NOT EXISTS code_hash text NOT NULL DEFAULT 'legacy-unknown';
ALTER TABLE public.research_observations ADD COLUMN IF NOT EXISTS config_hash text NOT NULL DEFAULT 'legacy-unknown';
ALTER TABLE public.research_observations ADD COLUMN IF NOT EXISTS intent jsonb;
CREATE TABLE IF NOT EXISTS public.paper_evaluations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, candidate_key text NOT NULL,
  evaluated_at timestamptz NOT NULL DEFAULT now(), fingerprint text NOT NULL,
  code_hash text NOT NULL, config_hash text NOT NULL, evidence jsonb NOT NULL,
  UNIQUE(candidate_key, fingerprint)
);
CREATE TABLE IF NOT EXISTS public.paper_account (
  id integer PRIMARY KEY CHECK(id = 1), risk_version text NOT NULL,
  equity numeric NOT NULL DEFAULT 10000, peak numeric NOT NULL DEFAULT 10000,
  day_key text NOT NULL DEFAULT '', daily_pnl numeric NOT NULL DEFAULT 0,
  open_risk numeric NOT NULL DEFAULT 0, locked boolean NOT NULL DEFAULT false,
  updated_at timestamptz NOT NULL DEFAULT now()
);
INSERT INTO public.paper_account(id, risk_version) VALUES(1, 'paper-risk-2026-09-25') ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS public.paper_releases (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, candidate_key text NOT NULL,
  activated_at timestamptz NOT NULL DEFAULT now(), evaluation_id bigint NOT NULL REFERENCES public.paper_evaluations(id),
  code_hash text NOT NULL, config_hash text NOT NULL,
  status text NOT NULL CHECK(status IN ('probation','active','paused')),
  reason text NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS paper_one_release ON public.paper_releases((true)) WHERE status IN ('probation','active');
CREATE TABLE IF NOT EXISTS public.paper_positions (
  id text PRIMARY KEY, release_id bigint NOT NULL REFERENCES public.paper_releases(id),
  opened_at timestamptz NOT NULL, closed_at timestamptz,
  symbol text NOT NULL CHECK(symbol IN ('MES','MNQ')), side text NOT NULL CHECK(side IN ('LONG','SHORT')),
  qty integer NOT NULL CHECK(qty > 0), entry numeric NOT NULL, stop numeric NOT NULL, target numeric NOT NULL,
  risk numeric NOT NULL CHECK(risk > 0), mark numeric NOT NULL, pnl numeric,
  reason text NOT NULL
);
ALTER TABLE public.paper_account ADD COLUMN IF NOT EXISTS day_start_equity numeric NOT NULL DEFAULT 10000;
ALTER TABLE public.paper_positions ADD COLUMN IF NOT EXISTS last_mark_ts timestamptz;
ALTER TABLE public.paper_account ADD COLUMN IF NOT EXISTS last_bar_ts timestamptz;
CREATE TABLE IF NOT EXISTS public.paper_entry_decisions (
  observation_key text PRIMARY KEY, decided_at timestamptz NOT NULL DEFAULT now(), reason text NOT NULL
);
CREATE TABLE IF NOT EXISTS public.research_confirmations (
  id text PRIMARY KEY, candidate_key text NOT NULL, measured_at timestamptz NOT NULL DEFAULT now(),
  code_hash text NOT NULL, config_hash text NOT NULL, outcome jsonb NOT NULL
);
CREATE OR REPLACE FUNCTION public.guard_research_observation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN RAISE EXCEPTION 'Research observations cannot be deleted'; END IF;
  IF NEW.observation_key <> OLD.observation_key OR NEW.candidate_key <> OLD.candidate_key
    OR NEW.strategy_version <> OLD.strategy_version OR NEW.source <> OLD.source
    OR NEW.provenance <> OLD.provenance OR NEW.first_seen_at <> OLD.first_seen_at
    OR NEW.code_hash <> OLD.code_hash OR NEW.config_hash <> OLD.config_hash OR NEW.intent IS DISTINCT FROM OLD.intent
    OR NEW.signal_ts <> OLD.signal_ts OR NEW.recovery_id IS DISTINCT FROM OLD.recovery_id
    OR (OLD.exit_ts IS NOT NULL AND (NEW.exit_ts IS DISTINCT FROM OLD.exit_ts OR NEW.payload <> OLD.payload))
  THEN RAISE EXCEPTION 'Research identity and closed outcomes are write-once'; END IF;
  RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS protect_observations ON public.research_observations;
CREATE TRIGGER protect_observations BEFORE UPDATE OR DELETE ON public.research_observations FOR EACH ROW EXECUTE FUNCTION public.guard_research_observation();
CREATE OR REPLACE FUNCTION public.guard_paper_evaluation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'Paper evaluations are append-only'; END $$;
DROP TRIGGER IF EXISTS protect_paper_evaluations ON public.paper_evaluations;
CREATE TRIGGER protect_paper_evaluations BEFORE UPDATE OR DELETE ON public.paper_evaluations FOR EACH ROW EXECUTE FUNCTION public.guard_paper_evaluation();
DROP TRIGGER IF EXISTS protect_confirmations ON public.research_confirmations;
CREATE TRIGGER protect_confirmations BEFORE UPDATE OR DELETE ON public.research_confirmations FOR EACH ROW EXECUTE FUNCTION public.guard_paper_evaluation();
DO $$ DECLARE t text; BEGIN
  FOREACH t IN ARRAY ARRAY['recovery_runs','research_observations','paper_evaluations','paper_account','paper_releases','paper_positions','paper_entry_decisions','research_confirmations'] LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t);
    EXECUTE format('GRANT SELECT ON public.%I TO anonymous, authenticated',t);
    IF NOT EXISTS(SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename=t AND policyname=t||'_read') THEN
      EXECUTE format('CREATE POLICY %I ON public.%I FOR SELECT TO anonymous, authenticated USING(true)', t||'_read',t);
    END IF;
  END LOOP;
END $$;
